fix: ensure branches exists (#13)

diff --git a/.github/workflows/merge-structure.yml b/.github/workflows/merge-structure.yml
--- a/.github/workflows/merge-structure.yml
+++ b/.github/workflows/merge-structure.yml
@@ -42,6 +42,28 @@ jobs:
   ensure-mergable:
     runs-on: ubuntu-slim
     steps:
+      - name: Ensure ${{ env.FROM }} branch exists
+        run: FROM_EXISTS=$(git branch -ra | grep "^\s*${{ env.FROM }}\s*$")
+          if [ "$FROM_EXISTS" = "" ];
+          then
+          echo "::error::The branch ${{env.FROM}} does not exist."
+          exit 1
+          fi
+
+      - uses: actions/checkout@v6
+        with:
+          ref: ${{ env.FROM }}
+      - name: Check if branch ${{ env.TO }} exists or create it from ${{ env.FROM }} and end workflow
+        run: TO_EXISTS=$(git branch -ra | grep "^\s*${{ env.TO }}\s*$")
+          if [ "$TO_EXISTS" = "" ];
+          then
+          echo "::notice::The branch ${{env.TO}} does not exist. Create it from ${{ env.FROM }}..."
+          git switch -c ${{ env.TO }}
+          git push ${{ github.repositoryUrl }} ${{ env.TO }}
+          echo "CANCELLED=1" >> $GITHUB_OUTPUT
+          exit 0
+          fi
+
       - uses: actions/checkout@v6
         with:
           ref: ${{ env.TO }}
@@ -72,10 +94,10 @@ jobs:
       - name: Verify versions
         run: if [ "$EXISTING_VERSION" = "$MERGIN_VERSION" ];
           then
-          echo Both versions matches. Cancelling all next jobs.
+          echo "::notice::Both versions matches. Cancelling all next jobs."
           echo "CANCELLED=1" >> $GITHUB_OUTPUT
           else
-          echo "Versions differ. Passing from '$EXISTING_VERSION' to '$MERGING_VERSION'."
+          echo "::notice::Versions differ. Passing from '$EXISTING_VERSION' to '$MERGING_VERSION'."
           fi
 
   # merge:
