fix: multiline syntax issues (#13)

diff --git a/.github/workflows/merge-structure.yml b/.github/workflows/merge-structure.yml
--- a/.github/workflows/merge-structure.yml
+++ b/.github/workflows/merge-structure.yml
@@ -43,36 +43,43 @@ jobs:
     runs-on: ubuntu-slim
     steps:
       - name: Ensure ${{ env.FROM }} branch exists
-        run: FROM_EXISTS=$(git branch -ra | grep "^\s*${{ env.FROM }}\s*$")
-          if [ "$FROM_EXISTS" = "" ]; then
-          echo "::error::The branch ${{env.FROM}} does not exist."
-          exit 1
+        run: |
+          FROM_EXISTS=$(git branch -ra | grep "^\s*${{ env.FROM }}\s*$")
+          if [ "$FROM_EXISTS" = "" ]; 
+          then
+            echo "::error::The branch ${{env.FROM}} does not exist."
+            exit 1
           fi
 
       - uses: actions/checkout@v6
         with:
           ref: ${{ env.FROM }}
       - name: Check if branch ${{ env.TO }} exists or create it from ${{ env.FROM }} and end workflow
-        run: TO_EXISTS=$(git branch -ra | grep "^\s*${{ env.TO }}\s*$")
-          if [ "$TO_EXISTS" = "" ]; then
-          echo "::notice::The branch ${{env.TO}} does not exist. Create it from ${{ env.FROM }}..."
-          git switch -c ${{ env.TO }}
-          git push ${{ github.repositoryUrl }} ${{ env.TO }}
-          echo "CANCELLED=1" >> $GITHUB_OUTPUT
-          exit 0
+        run: |
+          TO_EXISTS=$(git branch -ra | grep "^\s*${{ env.TO }}\s*$")
+          if [ "$TO_EXISTS" = "" ]; 
+          then
+            echo "::notice::The branch ${{env.TO}} does not exist. Create it from ${{ env.FROM }}..."
+            git switch -c ${{ env.TO }}
+            git push ${{ github.repositoryUrl }} ${{ env.TO }}
+            echo "CANCELLED=1" >> $GITHUB_OUTPUT
+            exit 0
           fi
 
       - uses: actions/checkout@v6
         with:
           ref: ${{ env.TO }}
       - name: Check mergability
-        run: git merge --no-ff --no-commit ${{ env.FROM }}
+        run: |
+          git merge --no-ff --no-commit ${{ env.FROM }}
           CONFLICTING=$(git diff --name-only --diff-filter=U --relative)
-          if [ ! "$CONFLICTING" = "" ]; then
-          echo "::error::Somes files are conflicting between branches ${{ env.FROM }} and ${{ env.TO }}."
-          echo "CANCELLED=1" >> $GITHUB_OUTPUT
-          exit 1;
+          if [ ! "$CONFLICTING" = "" ]; 
+          then
+            echo "::error::Somes files are conflicting between branches ${{ env.FROM }} and ${{ env.TO }}."
+            echo "CANCELLED=1" >> $GITHUB_OUTPUT
+            exit 1;
           fi
+
   check-version:
     runs-on: ubuntu-slim
     if: github.env.CHECK_VERSION && ! github.env.CANCELLED
@@ -89,11 +96,13 @@ jobs:
       - name: Fetch mergin version
         run: MERGING_VERSION=$(grep "version" ./package.json | grep -oP "\d.+(?=\")")
       - name: Verify versions
-        run: if [ "$EXISTING_VERSION" = "$MERGIN_VERSION" ]; then
-          echo "::notice::Both versions matches. Cancelling all next jobs."
-          echo "CANCELLED=1" >> $GITHUB_OUTPUT
-          else
-          echo "::notice::Versions differ. Passing from '$EXISTING_VERSION' to '$MERGING_VERSION'."
+        run: |
+          if [ "$EXISTING_VERSION" = "$MERGIN_VERSION" ]; 
+          then
+            echo "::notice::Both versions matches. Cancelling all next jobs."
+            echo "CANCELLED=1" >> $GITHUB_OUTPUT
+            else
+            echo "::notice::Versions differ. Passing from '$EXISTING_VERSION' to '$MERGING_VERSION'."
           fi
 
   # merge:
